[[understanding-jakarta-platform-enterprise-edition]]
== Understanding Jakarta EE Platform

This chapter describes the basic concepts behind enterprise application
development and examines how an application server is the sum of its
Jakarta EE containers.

[[overview-of-enterprise-applications]]
=== Overview of Enterprise Applications

This section describes enterprise applications and how they are designed
and developed.

As stated above, the Jakarta EE platform is designed to help developers
create large-scale, multitiered, scalable, reliable, and secure network
applications. A shorthand name for such applications is *enterprise
applications*, so called because these applications are designed to
solve the problems encountered by large enterprises. Enterprise
applications are not only useful for large corporations, agencies, and
governments, however. The benefits of an enterprise application are
helpful, even essential, for individual developers and small
organizations in an increasingly networked world.

The features that make enterprise applications powerful, like security
and reliability, often make these applications complex. The Jakarta EE
platform reduces the complexity of enterprise application development by
providing a development model, API, and runtime environment that allow
developers to concentrate on functionality.

[[tiered-applications]]
==== Tiered Applications

In a multitiered application, the functionality of the application is
separated into isolated functional areas, called tiers. Typically,
multitiered applications have a client tier, a middle tier, and a data
tier (often called the enterprise information systems tier). The client
tier consists of a client program that makes requests to the middle
tier. The middle tier is divided into a web tier and a business tier,
which handle client requests and process application data, storing it in
a permanent data store in the data tier.

Jakarta EE application development concentrates on the middle tier to make
enterprise application management easier, more robust, and more secure.

[[the-client-tier]]
===== The Client Tier

The client tier consists of application clients that access a Jakarta EE
server and that are usually located on a different machine from the
server. The clients make requests to the server. The server processes
the requests and returns a response back to the client. Many different
types of applications can be Jakarta EE clients, and they are not always,
or even often, Java applications. Clients can be a web browser, a
standalone application, or other servers, and they run on a different
machine from the Jakarta EE server.

[[the-web-tier]]
===== The Web Tier

The web tier consists of components that handle the interaction between
clients and the business tier. Its primary tasks are the following:

* Dynamically generate content in various formats for the client
* Collect input from users of the client interface and return
appropriate results from the components in the business tier
* Control the flow of screens or pages on the client
* Maintain the state of data for a user's session
* Perform some basic logic and hold some data temporarily in managed
beans

The following table lists some of the main Jakarta EE technologies that
are used in the web tier in Jakarta EE applications.

.*Web-Tier Jakarta EE Technologies*
[cols="25%,74%"]
|=======================================================================
|*Technology* |*Purpose*
|Jakarta Server Faces technology |A user interface component framework for
web applications that allows you to include UI components (such as
fields and buttons) on a XHTML page, called a Facelets page; convert and
validate UI component data; save UI component data to server-side data
stores; and maintain component state

|Expression Language |A set of standard tags used in Facelets pages to
refer to Jakarta EE components

|Servlets |Java programming language classes that dynamically process
requests and construct responses, usually for HTML pages

|Jakarta Contexts and Dependency Injection |A set of contextual
services that make it easy for developers to use enterprise beans along
with JavaServer Faces technology in web applications
|=======================================================================


[[the-business-tier]]
===== The Business Tier

The business tier consists of components that provide the business logic
for an application. Business logic is code that provides functionality
to a particular business domain, like the financial industry, or an
e-commerce site. In a properly designed enterprise application, the core
functionality exists in the business tier components.

The following Jakarta EE technologies are among those that are used in the
business tier in Jakarta EE applications:

* Jakarta Enterprise Beans components
* Jakarta RESTful Web Services
* Jakarta Persistence entities

[[the-enterprise-information-systems-tier]]
===== The Enterprise Information Systems Tier

The enterprise information systems (EIS) tier consists of database
servers, enterprise resource planning systems, and other legacy data
sources, like mainframes. These resources typically are located on a
separate machine from the Jakarta EE server, and are accessed by components
on the business tier.

The following Jakarta EE technologies are used to access the EIS tier in
Jakarta EE applications:

* The Java Database Connectivity API (JDBC)
* Jakarta Persistence
* Jakarta Connectors
* Jakarta Transactions

[[jakarta-ee-servers-and-containers]]
==== Jakarta EE Servers and Containers

A Jakarta EE server is a server application that implements the Jakarta EE
platform APIs and provides standard Jakarta EE services. Jakarta EE servers
are sometimes called application servers, because they allow you to
serve application data to clients, much as web servers serve web pages
to web browsers.

Jakarta EE servers host several application component types that correspond
to the tiers in a multitiered application. The Jakarta EE server provides
services to these components in the form of a container.

Jakarta EE containers are the interface between the component and the
lower-level functionality provided by the platform to support that
component. The functionality of the container is defined by the platform
and is different for each component type. Nonetheless, the server allows
the different component types to work together to provide functionality
in an enterprise application.

[[the-web-container]]
==== The Web Container

The web container is the interface between web components and the web
server. A web component can be a servlet or a Jakarta Server Faces Facelets
page. The container manages the component's life cycle, dispatches
requests to application components, and provides interfaces to context
data, such as information about the current request.

[[the-ejb-container]]

==== The enterprise bean Container

The enterprise bean container is the interface between enterprise beans, which
provide the business logic in a Jakarta EE application, and the Jakarta EE
server. The enterprise bean container runs on the Jakarta EE server and manages the
execution of an application's enterprise beans.

[[the-application-client-container]]

==== The Application Client Container

The application client container is the interface between Jakarta EE
application clients (special Java SE applications that use Jakarta EE
server components) and the Jakarta EE server. The application client
container runs on the client machine and is the gateway between the
client application and the Jakarta EE server components that the client
uses.
