[[preface]]
== Preface

This is Your First Cup: An Introduction to Jakarta EE Platform,
a short tutorial for beginning Jakarta EE programmers. This
tutorial is designed to give you a hands-on lesson on developing an
enterprise application from initial coding to deployment.

[[audience]]
=== Audience

This tutorial is intended for novice Jakarta EE developers. You should be
familiar with the Java programming language, particularly the features
introduced in Java Platform, Standard Edition 8. While familiarity with
enterprise development and Jakarta EE technologies is helpful, this
tutorial assumes you are new to developing Jakarta EE applications.


[[before-you-read-this-book]]
=== Before You Read This Book

Before you start this tutorial, you should:

* Be familiar with the Java programming language
* Be able to install software on your work machine
* Have a modern web browser installed on your work machine

[[related-books-and-projects]]
=== Related Books and Projects

The following books and projects may be helpful to you in understanding
this tutorial:

* The https://eclipse-ee4j.github.io/jakartaee-tutorial/[Jakarta EE Tutorial]
* The GlassFish documentation set
* The Apache NetBeans IDE documentation

[[conventions]]
=== Conventions

The following table describes the typographic conventions that are used
in this book.

[cols="20%,39%,39%"]
|=======================================================================
|*Convention* |*Meaning* |*Example*
|*Boldface* |Boldface type indicates graphical user interface elements
associated with an action, or terms defined in text. a|
From the *File* menu, select *New Project*.

A *cache* is a copy that is stored locally.

|`Monospace` |Monospace type indicates the names of files and
directories, commands within a paragraph, URLs, code in examples, text
that appears on the screen, or text that you enter. a|
Edit your `.login` file.

Use `ls -a` to list all files.

`_machine_name_% you have mail.`

|_Italic_ |Italic type indicates book titles, emphasis, or placeholder
variables for which you supply particular values. a|
The command to remove a file is `rm _filename_`.

Read Chapter 6 in the _User's Guide_.

Do _not_ save the file.

|=======================================================================
