type=page
status=published
title=Prerequisite Tasks for Completing This Tutorial
next=jakarta-ee.html
prev=intro001.html
~~~~~~
= Prerequisite Tasks for Completing This Tutorial


[[GCQZL]][[prerequisite-tasks-for-completing-this-tutorial]]

Prerequisite Tasks for Completing This Tutorial
-----------------------------------------------

To complete this tutorial, you need to complete the following tasks
first:

* link:#software-compatibility[See the software compatibility notice]
* link:#get-the-jakarta-ee-8-sdk[Get the Jakarta EE 8 SDK]
* link:#install-the-eclipse-ide-distribution-for-java-ee[Install the Eclipse IDE for Enterprise Java Developers]
* link:#add-glassfish-server-as-a-server-in-eclipse-ide[Add GlassFish Server as a server in Eclipse IDE]
////
* link:#get-the-latest-updates-to-this-tutorial[Get the latest updates to this tutorial]
////

[[software-compatibility]]

Software Compatibility Notice
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

This tutorial is compatible with the following software:

[width="55%",cols="30%,60%"]
|=======================================================================
|*Software* |*Version*
|link:http://www.oracle.com/technetwork/java/javase/downloads/index.html[Java Development Kit (JDK)] | 8 update 144 (8u144) or greater
|link:https://javaee.github.io/glassfish/[GlassFish Server] | 5.0 or greater
|link:https://eclipse.org/ide/[Eclipse IDE] | 4.7.0 or greater

|=======================================================================

[[GCRNX]][[get-the-jakarta-ee-8-sdk]]

Get the Jakarta EE 8 SDK
~~~~~~~~~~~~~~~~~~~~~~~~

To get the Jakarta EE 8 SDK, go to
`http://www.oracle.com/technetwork/java/jakartaee/downloads/`. Download and
install the SDK. The location where you install it is typically
`glassfish5` in your home directory, but you can change this.

The tutorial is installed in the `docs/firstcup` directory of your SDK
installation.

[[GCRNU]][[install-the-eclipse-ide-distribution-for-java-ee]]

Install the Eclipse IDE for Enterprise Java Developers
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

To get Eclipse IDE, go to `https://www.eclipse.org/downloads/` and
download the Enterprise Java Developers distribution through the installer or available packages.
Install this distribution.

[[GIOEW]][[add-glassfish-server-as-a-server-in-eclipse-ide]]

Add GlassFish Server as a Server in Eclipse IDE
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Once you have all the necessary downloads, you must configure Eclipse
IDE and get the latest tutorial updates.

To run this tutorial in Eclipse IDE, you must register your GlassFish
Server installation as a Eclipse server instance. Follow these
instructions to register the GlassFish Server in Eclipse IDE.

First of all it's needed to install Eclipse Sapphire, to install just follow the instructions:
`https://download.eclipse.org/sapphire/9.1.1/repository/`

After that just install GlassFish Tools it's the same process:
`https://download.eclipse.org/glassfish-tools/1.0.1/repository/`

Now we can add GlassFish as a server in Eclipse IDE

1.  From the *File* > *New* > *Other...*, search for *Server*, select and click next.
2.  In the New Server dialog, search for *Glassfish*, select *GlassFish* and click next.
3.  Under *GlassFish Location*, browse to or enter the location of your
GlassFish Server installation.
4.  If *Java location* it's not automatically identified, look for the folder where your java
is installed.
5.  Under *Define GlassFish Application Server properties*, leave the default options.
6.  Then click *Finish*.

////
[[GIMVN]][[get-the-latest-updates-to-this-tutorial]]

Get the Latest Updates to this Tutorial
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Check for any updates to this tutorial by using the Update Center
included with the Jakarta EE 8 SDK.

1.  In NetBeans IDE, select the *Services* tab and expand the *Servers*
node.
2.  Right-click the GlassFish Server instance and select *View Domain
Update Center* to display the Update Tool.
3.  In the tree, select *Available Updates* to display a list of updated
packages.
4.  Look for updates to the First Cup for Jakarta EE 8
(`jakartaee-firstcup-tutorial`) package.
5.  If there is an updated version, select First Cup for Jakarta EE 8
(`jakartaee-firstcup-tutorial`) and click *Install*.
////
