type=page
status=published
title=Building, Packaging, Deploying, and Running the firstcup-war Web Application
next=next-steps.html
prev=web-application005.html
~~~~~~
= Building, Packaging, Deploying, and Running the firstcup-war Web Application


[[GCTNX]][[building-packaging-deploying-and-running-the-firstcup-war-web-application]]

Building, Packaging, Deploying, and Running the firstcup-war Web Application
----------------------------------------------------------------------------

In this section, you will build the `firstcup-war` web application,
deploy it to the server, and run the application.

[[GCTOJ]][[build-package-and-deploy-the-firstcup-war-web-application]]

Build, Package, and Deploy the firstcup-war Web Application
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Before we finish, we need to create a run configuraton to start the embedded
database for us.

1. Go to *Run* -> *External Tools* -> *External Tools Configurations...*.
2. At *External Tools Configuration* dialog click in *Program* and *New launch configuration* icon.
3. Then give a name to the shortcut at field *Name:*.
4. At *Location:* field click in *Browse File System...* and search for your GlassFish installation.
5. In your Glassfish installation root folder, go to bin folder.
6. Select `asadmin.bat` if you are in Windows, otherwise select `asadmin.sh` and click *OK*.
7. In *Arguments:* text area put `start-database`.
8. Click *Apply* and *Run*.

Now the internal database is already running.


Now build and package the `DukesBirthdayBean` enterprise bean, the
`FirstcupUser` entity, and the `firstcup-war` web client into a WAR
file, `firstcup-war.war`, then deploy it to the server.


1. Click the *Servers* tab.
2. Right-click the GlassFish Server instance and go to *Add and Remove...*.
3. At *Add and Remove...* dialog, select the `firstcup-war` artifact and click *Add >*.
4. Click *Finish*.
5. Right-click the GlassFish Server instance and click *Start*.

After `firstcup-war.war` deploys successfully to GlassFish Server,
go to `http://localhost:8080/firstcup-war/` url.

[[GCTQC]][[run-the-firstcup-war-application]]

Run the firstcup-war Application
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

1.  On the greeting page, enter your birth date in the *Your birthday*
field. Make sure you use the date pattern specified on the page:
MM/dd/yyyy.
2.  Click *Submit*.
3.  After the `response.xhtml` page is displayed, click *Back* to return
to the `greeting.xhtml` page.
4.  Enter a different birthday in the text field and click *Submit* again
to see how the average age of First Cup users changes.

Congrats !