type=page
status=published
title=Creating the Web Application Project Using the Archetype
next=web-application003.html
prev=web-application001.html
~~~~~~
= Creating the Web Application Project Using the Archetype


[[GIMNT]][[creating-the-web-application-project-using-the-archetype]]

Creating the Web Application Project Using the Archetype
--------------------------------------------------------

Follow these steps to create a new web application project using the
`firstcup-war-archetype` in Eclipse IDE.

1. From the *File* menu, select *New* -> *Maven Project*.
2. Under *New Maven Project* dialog, click  *Next*.
3. In the *Filter* field, enter `firstcup` and check the *Include snapshot
archetypes*.
4. Select `firstcup-war-archetype` and click *Next*.
5. In the *Group Id* field, enter `jakarta.firstcup`.
6. In the *Artifact Id* field, enter `firstcup-war`.
7. In the *Package* field, enter `jakarta.firstcup.firstcupwar`.
8. Click *Finish*.

+
You should now see the module you created in the *Project Explorer* tab.

The `firstcup-war-archetype` archetype creates the structure of the web
application, including the following:

* Basic entity classes
* Basic enterprise bean classes
* Basic backing bean classes
* Basic Facelets XHTML components and views
* The `web.xml`, `faces-config.xml`, and `persistence.xml` deployment
descriptors

After you create the basic application structure with the archetype, you
will configure how the application will run, implement the functionality
of the classes, implement the Facelets views, and then deploy the
application.
